[package]
name = "acmer-oj"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
libc = "0.2.161"
nix = { version = "0.29.0", features = ["user"] }
tokio = { version = "1.41.0", features = ["full"] }
